---
istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
    passthrough-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        service:
          ports:
            - port: 15022
              name: status-port
              protocol: TCP
            - port: 81
              targetPort: 8080
              name: http2
              protocol: TCP
            - port: 444
              targetPort: 8443
              name: https
              protocol: TCP

  gateways:
    public:
      ingressGateway: "public-ingressgateway"
      hosts:
        - "*.bigbang.dev"
    passthrough:
      ingressGateway: "passthrough-ingressgateway"
      hosts:
        - "*.bigbang.dev"
      tls:
        mode: "PASSTHROUGH"
